### PR TITLE
Updated code for Windows

### PR DESCRIPTION
**Pull request by vinogcs**
I got few plans too. Let's plan in further commits.

### CODE REVIEW

**Comment by amit-bhandari** [comment]
Hey Vinoth, thanks for the pull request. I will just quickly check it once in my windows desktop later in the evening and will merge it with the master.

**Comment by amit-bhandari** [comment]
Let me know what are your further plans.

**Comment by vinogcs** [comment]
As a start, we can have a separate file as "keywords" where user can add any keyword he/she wants (one per line). We'll fetch randomly one keyword and download image instead of same keywords. 

Or other thought, we can have a db of keywords saved based on moods. So user can just select any mood and we'll fetch keyword based on mood and update wallpaper. 

We can give configuring options  in terminal so that users wont need to open source codes. ;) 
It'll go on and on..

**Comment by amit-bhandari** [comment]
Sounds excellent, I think idea of mentioning keywords in file sounds good. We will give option to give file as input instead of single keyword.

**Pull request merged**
